# Site settings
title: Humanitas
email: aezua@humanitas.us
description: > 
  Examining the well-lived life of thoughtful compassion and genuine
  self-reflection for the betterment of the all that exist.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://humanitas.us" # the base hostname & protocol for your site
paginate: 5
exclude: [Gemfile, Gemfile.lock]

name: 'Gabriel McArthur'
github_username: aezua

collections:
  poems:
    output: true

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
